/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.PrincipalControl;
import Model.FachadaModels;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author humbe
 */
public class JPrincipal extends javax.swing.JFrame {

    private FachadaModels model;

    
    public JPrincipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    public JPrincipal(FachadaModels model) {
        this();
        
        if (model != null) {
            this.model = model;
        } else {
            this.model = new FachadaModels();
        }
    }

    
    private void centralizarTela(JInternalFrame frame){
        Dimension desktopSize = this.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPaciente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSala = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsulta = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRecepcionista = new javax.swing.JMenuItem();
        jMenuVerificarMedico = new javax.swing.JMenu();
        jMenuItemVerificarMedico = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerificarPaciente = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerificarSala = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerificarConsulta = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerificarRecepcionista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        javax.swing.GroupLayout jDesktopPanePainelLayout = new javax.swing.GroupLayout(jDesktopPanePainel);
        jDesktopPanePainel.setLayout(jDesktopPanePainelLayout);
        jDesktopPanePainelLayout.setHorizontalGroup(
            jDesktopPanePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        jDesktopPanePainelLayout.setVerticalGroup(
            jDesktopPanePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jMenuCadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\clipboard.png")); // NOI18N
        jMenuCadastrar.setText("Cadastrar");
        jMenuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarActionPerformed(evt);
            }
        });

        jMenuItemMedico.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\doctor.png")); // NOI18N
        jMenuItemMedico.setText("Médico");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemMedico);
        jMenuCadastrar.add(jSeparator1);

        jMenuItemPaciente.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\patient.png")); // NOI18N
        jMenuItemPaciente.setText("Paciente");
        jMenuItemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemPaciente);
        jMenuCadastrar.add(jSeparator2);

        jMenuItemSala.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\hospital.png")); // NOI18N
        jMenuItemSala.setText("Sala");
        jMenuItemSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemSala);
        jMenuCadastrar.add(jSeparator3);

        jMenuItemConsulta.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\serum.png")); // NOI18N
        jMenuItemConsulta.setText("Consulta");
        jMenuItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemConsulta);
        jMenuCadastrar.add(jSeparator4);

        jMenuItemRecepcionista.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\receptionist.png")); // NOI18N
        jMenuItemRecepcionista.setText("Recepcionista");
        jMenuItemRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecepcionistaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemRecepcionista);

        jMenuBar1.add(jMenuCadastrar);

        jMenuVerificarMedico.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\research.png")); // NOI18N
        jMenuVerificarMedico.setText("Verificar");

        jMenuItemVerificarMedico.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\doctor.png")); // NOI18N
        jMenuItemVerificarMedico.setText("Médico");
        jMenuItemVerificarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerificarMedicoActionPerformed(evt);
            }
        });
        jMenuVerificarMedico.add(jMenuItemVerificarMedico);
        jMenuVerificarMedico.add(jSeparator5);

        jMenuItemVerificarPaciente.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\patient.png")); // NOI18N
        jMenuItemVerificarPaciente.setText("Paciente");
        jMenuItemVerificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerificarPacienteActionPerformed(evt);
            }
        });
        jMenuVerificarMedico.add(jMenuItemVerificarPaciente);
        jMenuVerificarMedico.add(jSeparator6);

        jMenuItemVerificarSala.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\hospital.png")); // NOI18N
        jMenuItemVerificarSala.setText("Sala");
        jMenuItemVerificarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerificarSalaActionPerformed(evt);
            }
        });
        jMenuVerificarMedico.add(jMenuItemVerificarSala);
        jMenuVerificarMedico.add(jSeparator7);

        jMenuItemVerificarConsulta.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\serum.png")); // NOI18N
        jMenuItemVerificarConsulta.setText("Consulta");
        jMenuVerificarMedico.add(jMenuItemVerificarConsulta);
        jMenuVerificarMedico.add(jSeparator8);

        jMenuItemVerificarRecepcionista.setIcon(new javax.swing.ImageIcon("C:\\Users\\humbe\\Desktop\\receptionist.png")); // NOI18N
        jMenuItemVerificarRecepcionista.setText("Recepcionista");
        jMenuVerificarMedico.add(jMenuItemVerificarRecepcionista);

        jMenuBar1.add(jMenuVerificarMedico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePainel)
        );

        setBounds(811, 557, 748, 485);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVerificarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerificarSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVerificarSalaActionPerformed

    private void jMenuItemVerificarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerificarMedicoActionPerformed
        JIFVerificarMedico view = new JIFVerificarMedico(this.model);
        jDesktopPanePainel.add(view);
        this.centralizarTela(view);
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerificarMedicoActionPerformed

    private void jMenuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrarActionPerformed

    private void jMenuItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaActionPerformed

    }//GEN-LAST:event_jMenuItemConsultaActionPerformed

    private void jMenuItemSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalaActionPerformed
        JIFCadastrarSala view = new JIFCadastrarSala(this.model);
        jDesktopPanePainel.add(view);
        this.centralizarTela(view);
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemSalaActionPerformed

    private void jMenuItemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteActionPerformed
        JIFCadastrarPaciente view = new JIFCadastrarPaciente(this.model);
        jDesktopPanePainel.add(view);
        this.centralizarTela(view);
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemPacienteActionPerformed

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
        JIFCadastrarMedico view = new JIFCadastrarMedico(this.model);
        jDesktopPanePainel.add(view);
        this.centralizarTela(view);
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jMenuItemRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRecepcionistaActionPerformed

    private void jMenuItemVerificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerificarPacienteActionPerformed
       JIFVerificarPaciente view = new JIFVerificarPaciente(this.model);
       jDesktopPanePainel.add(view);
       this.centralizarTela(view);
       view.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerificarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuItemConsulta;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JMenuItem jMenuItemRecepcionista;
    private javax.swing.JMenuItem jMenuItemSala;
    private javax.swing.JMenuItem jMenuItemVerificarConsulta;
    private javax.swing.JMenuItem jMenuItemVerificarMedico;
    private javax.swing.JMenuItem jMenuItemVerificarPaciente;
    private javax.swing.JMenuItem jMenuItemVerificarRecepcionista;
    private javax.swing.JMenuItem jMenuItemVerificarSala;
    private javax.swing.JMenu jMenuVerificarMedico;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
